---

- name: Install ntopng_extra_packages
  yum:
    name: "{{ ntopng_extra_packages }}"
    state: present

- name: Install ntopng_package
  yum:
    name: "{{ ntopng_package }}"
    state: present

- name: Enable ntopng_service
  service:
    name: "{{ ntopng_service }}"
    enabled: yes

- name: "Create /etc/sysconfig/{{ ntopng_service }}"
  template:
    src: RedHat.sysconfig.j2
    dest: "/etc/sysconfig/{{ ntopng_service }}"
    mode: 0644
    # keep the original copy in case you need the defaults in it
    backup: yes
    validate: sh -n %s
  notify:
    - Restart ntopng_service
